//model pojazdu i definicje podmodeli:
models: aks_s.t3d
animations: 4 4 0 0 2 2 -1
lowpolyinterior: aks_s-lowpoly
//ruchome czesci (animations)
//krecace sie kola (o srednicy jak w *.chk)
animwheelprefix: wheel0
animdoorprefix: door0
//patyki
animpantrd1prefix: pantrd1_pant0
animpantrg1prefix: pantrg1_pant0
animpantrd2prefix: pantrd2_pant0
animpantrg2prefix: pantrg2_pant0
animpantslprefix: slizg_pant0
pantfactors: 0 0 0.06986 0.06986
// aktualnie mozna jeszcze animrodprefix, animpendulumprefix, 
endmodels

locations:
 doors: -4.52 both 4.52 both end
 bogies: -7.935 7.935 end
 tractionmotors: -7.992 7.992 end
endlocations

sounds:
curve: {
 amplitudefactor: 1.15
 amplitudeoffset: 1.25
 range: 100
 crossfade: 75
 sound1: 697_104e_curve_1.wav
 sound30: 697_en57-skrzypi.wav
 sound35: curve_en57-1.wav
 sound60: curve_en57.wav
sound80: curve_en57.wav }
wheel_clatter: 35 -9.28 20786_en57_wheel_5.wav -6.58 20786_en57_wheel_6.wav 6.58 20786_en57_wheel_7.wav 9.28 20786_en57_wheel_8.wav end
tractionmotor: {
 amplitudeoffset: 0.6
 amplitudefactor: 1.2
 frequencyfactor: 0.024
 range: 75
 crossfade: 75
 sound1: silence1.wav pitch1: 1
 sound11: gmeinder_90hz.wav pitch11: 11
 sound39: gmeinder_330hz3.wav pitch39: 39
 sound61: gmeinder_530hz.wav pitch61: 61
 sound97: gmeinder_830hz.wav pitch97: 97
 sound291: silence1.wav pitch291: 291 }
tractionacmotor: {
 placement: external
 range: 75
 pitchvariation: 0
 amplitudefactor: 0.7
 amplitudeoffset: 0.0
 frequencyfactor: 1
 frequencyoffset: 0 
 crossfade: 75
 sound1: silence1.wav pitch1: 0.01
 sound70: 36wea_f700.wav pitch70: 0.7
 sound100: 36wea_f1000.wav pitch100: 1
 sound130: 36wea_f1300.wav pitch130: 1.3
 sound131: 36wea_f800_2faza.wav pitch131: 1.31
 sound200: 36wea_f1300.wav pitch200: 2.0
 sound270: silence1.wav  pitch270: 2.7 }
include brake_external.inc end
include brakesound_external.inc end
derail: derail.wav 200
converter: { soundmain: 2193_en57ak_rwn.wav range: 50 placement: external amplitudeoffset: -0.3 offset: [-0.5,0.56,-2.5]}
motorblower: { soundbegin: 2193_en57ak_vent1.wav soundmain: 2193_en57ak_vent2.wav soundend: 2193_en57ak_vent3.wav range: 50 placement: external }
small-compressor: s-compressor-start.wav,s-compressor.wav,s-compressor-stop.wav 20
pantographup: 24150_eu07_pantograf_dosieci.flac
pantographdown: pantdown.wav
dooropen: { soundmain: 22657_en57al_door_open.wav range: 20 }
doorclose: { soundmain: 22657_en57al_door_close.wav range: 20 }
outernoise: {
 range: 130
 crossfade: 85
 sound0: silence1.wav pitch0: 35
 sound35: 697_en57_outernoise_35.wav pitch35: 35
 sound80: 697_en57_outernoise_80.wav pitch80: 40
 sound200: 697_en57_outernoise_80.wav pitch200: 80 }
unloading: 24150_en57_pasazery.flac
loading: 24150_en57_pasazery.flac
releaser: releaser_1.wav releaser_2.wav releaser_3.wav 15 
sand: 20786_es64x4_sand_1.wav 20786_es64x4_sand_2.wav 20786_es64x4_sand_3.wav 25
brakecylinderinc: { range: 20 [ soundproofing: 0.2 0.5 0.2 0.8 0.8 0.8 ]
 sound1: 2193_en57-brakecyl-begin
 sound2: 2193_en57-brakecyl-low pitch2: 1.1
 sound5: 2193_en57-brakecyl-low pitch5: 1.0
 sound6: 2193_en57-brakecyl-high pitch6: 1.0
 sound9: 2193_en57-brakecyl-high pitch9: 0.9 }
 unbrake: { range: 20 soundbegin: 697_en57-luz-start.wav soundmain: 697_en57-luz-trwa.wav soundend: 697_en57-luz-koniec.wav soundproofing: [ 0.1 0.5 0.1 0.8 0.8 0.8 }
announcements: {
 near_stop: sip/zblizamy_sie_do_stacji.wav
 stop: sip/stacja.wav 
 next_stop: sip/nastepna_stacja.wav 
 destination: sip/stacja_docelowa.wav 
 chime: sip/jingiel_rg.wav
}
endsounds

internaldata:
//to jest sekcja odnoszaca sie do wnetrza pojazdu w ktorym jestesmy (odpowiednik dawnego pliku internal.mmd)

// dzwieki:
rainsound: { sound0: rainsound_default.wav sound30: rain_normal.wav sound70: rain_heavy.wav amplitudefactor: 0.5 }
pneumaticrelay: pneumaticrelay.wav
pneumaticswitch: en71_stycznik_2.wav
couplerattach: [ couplerattach.wav 697_hak_zakladanie.wav ]
couplerdetach: 24150_pg_otwarcie_kurka.wav
couplerstretch: { soundmain: [ en57_tarcie_gum_2.wav en57_tarcie_gum.wav ] placement: internal }
bufferclamp: en57_bufferclamp.wav
slipperysound: brake-slipp.wav 2.0 0.2  //normalized: AM/Vmax
airsound: hiss-en57.wav 1.0 -0.1  //unnormalized
runningnoise: {
 range: -1
 amplitudefactor: 0.7
 amplitudeoffset: 0.3
 crossfade: 70
 sound0: silence1.wav pitch0: 30
 sound10: akm_runningnoise_20.wav pitch10: 30
 sound20: akm_runningnoise_20.wav pitch20: 40
 sound30: akm_runningnoise_30.wav pitch30: 40
 sound40: akm_runningnoise_40a.wav pitch40: 40
 sound50: akm_runningnoise_50a.wav pitch50: 50
 sound60: akm_runningnoise_60a.wav pitch60: 60
 sound70: akm_runningnoise_70a.wav pitch70: 70
 sound80: akm_runningnoise_80a.wav pitch80: 80
 sound90: akm_runningnoise_90a.wav pitch90: 90
 sound100: akm_runningnoise_90a.wav pitch100: 100
 sound120: akm_runningnoise_90a.wav pitch120: 120
 sound200: akm_runningnoise_115a.wav pitch200: 200 }
 
 include brakesound_internal.inc end

cab1definition:   //rozmiary kabiny po ktorej mozna chodzic
-1.2 1.1 3.5
 1.2 1.1 10.0 
driver1pos:       // pozycja poczatkowa 
0.0 2.8 8.0

cab0definition:
 -1.2 1.1 -5.5
  1.2 1.1  5.5
driver0pos:
0.0 2.8 0.0

cab2definition: 
 -1.2 1.1 -10.0
  1.2 1.1  -3.5 
driver2pos: 
0.0 2.8 -8.0
