brakesound: {
 amplitudefactor: 2.1
 amplitudeoffset: 0.1 
 range: 130
 crossfade: 85
 placement: external
 soundproofing: [ 0 0.1 0 1 1 1 ]
 sound0: silence1.wav
 sound15: brake-15.wav
 sound25: brake-25.wav
 sound30: brake-30.wav
 sound40: brake-40.wav
 sound50: brake-50.wav
 sound60: brake-60.wav
 sound80: brake-80.wav
 sound100: brake-100.wav
 sound130: brake-130.wav 
 sound200: brake-130.wav }