brakesound: {
 amplitudefactor: 0.9
 amplitudeoffset: 0.0
 frequencyfactor: 1.1
 frequencyoffset: 0.0
 placement: internal 
 crossfade: 90
 sound0: silence1.wav
 sound10: en57akm_bs10.wav
 sound20: en57akm_bs20.wav
 sound35: en57akm_bs35.wav
 sound50: en57akm_bs50.wav
 sound60: en57akm_bs60.wav
 sound85: en57akm_bs85.wav
 sound100: en57akm_bs100.wav
 sound120: en57akm_bs120.wav
 sound200: en57akm_bs120.wav }